server:
  servlet:
    session:
      tracking-modes: cookie
  port: 9000

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=frombusan
    username: system
    password: 4604
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size:
        2000MB

      max-request-size:
        5000MB

mybatis:
#  type-aliases-package: com.example.board.model
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:config/mybatis-config.xml
  
    
  